update default python version for packs to be a list
StackStorm-Exchange/ci pull request #143
Opened 2023-10-23 02:13 UTC by sravs-dev

2023-10-23 02:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm-Exchange/ci?pullRequest=143) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm-Exchange/ci?pullRequest=143) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm-Exchange/ci?pullRequest=143) it.</sub>

2023-10-23 18:00 UTC, armab reviewed
@sravs-dev  Thanks for the PR!

Let's verify if it works in a pack CI.
You can open a PR in some Exchange pack repo. Let's pick up `Github` pack, the workflow is here: https://github.com/StackStorm-Exchange/stackstorm-github/blob/master/.github/workflows/build_and_test.yaml#L13
You can open a PR changing the ref to your fork with a branch.

That should use this GH Workflow and we can verify if it works OK.

Please also sign CLA.

2023-10-24 00:20 UTC, cognifloyd requested changes

2023-10-24 00:20 UTC, cognifloyd commented on .github/workflows/pack-build_and_test.yaml
> +        default: ["3.6","3.8","3.9"]
Changing the type from string to array here would mean we have to change the matrix definition below. There, we are using `matrix.include` to add one entry for the indicated python version.

The docs about `matrix.include` are here.: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations

2023-12-02 09:38 UTC, sravs-dev commented
@armab I have signed the CLA, but it still shown as pending. Could you please help?

2023-12-03 07:52 UTC, sravs-dev commented
@armab opened a new [PR](https://github.com/StackStorm-Exchange/ci/pull/145) to resolve commit log issues. Closing this one

2023-12-03 07:52 UTC, closed without merging